package com.estimate_java_object_size;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.util.DefaultInstantiatorStrategy;
import com.estimate_java_object_size.model.*;
import com.salesforce.ObjectSizer;
import org.HdrHistogram.AtomicHistogram;
import org.apache.commons.lang3.RandomStringUtils;
import org.objenesis.strategy.StdInstantiatorStrategy;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;


public class Tester2 {

    public static void main(String[] args) throws NoSuchFieldException, IllegalAccessException {

        String str = "testval";
        String str4 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ipsum enim, tempor nec dapibus ut, laoreet at ligula. Duis placerat, nisi in venenatis commodo, leo velit mattis nisi, ut cursus dui tortor et nisi. Pellentesque nec odio nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis scelerisque sapien non maximus. Mauris nulla leo, bibendum et eleifend quis, rhoncus a magna. In felis nunc, maximus ac ligula nec, gravida feugiat neque. Cras feugiat, erat at mattis dapibus, mi orci aliquam nibh, eget rhoncus arcu justo non est. Pellentesque a nunc at est malesuada tincidunt non et neque. Vestibulum commodo mauris et nisl blandit, ac tristique massa eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc bibendum fermentum elementum. Curabitur efficitur gravida tincidunt. Maecenas cursus sem sit amet condimentum cursus. Nam posuere augue non lorem sagittis aliquet.\n" +
                "\n" +
                "Donec ex enim, placerat eget quam sit amet, tincidunt fringilla nulla. Vestibulum porta velit sit amet elementum congue. Praesent eget diam vel lectus congue volutpat. Vestibulum nec gravida arcu, a rhoncus purus. Nulla auctor nisl a varius volutpat. Vestibulum eget ultricies diam. Vivamus et sollicitudin arcu, eget egestas arcu. Donec ut interdum enim, vehicula porttitor risus. Pellentesque quis fermentum mi, ac imperdiet nisi.\n" +
                "\n" +
                "Phasellus venenatis libero at sapien vestibulum bibendum. Curabitur enim nisi, feugiat at mi in, consectetur condimentum magna. Integer eu ornare dui, ac hendrerit elit. Mauris sit amet ex quis magna ornare tincidunt non quis dui. Etiam arcu tellus, tincidunt ultrices vulputate eget, fringilla nec mi. Mauris tristique interdum sapien, vitae ultricies mauris porttitor ut. Fusce vitae tristique lectus, sed aliquet nisl. Cras tincidunt dui ut urna efficitur iaculis. Vivamus sit amet arcu eget velit convallis faucibus vitae sit amet mi. Praesent porttitor quam eget lectus consequat dictum. Donec eros neque, interdum nec tortor a, congue varius nulla.\n" +
                "\n" +
                "Maecenas suscipit aliquet nunc at dapibus. Etiam nibh risus, imperdiet sed lacus lobortis, semper rhoncus risus. Proin quis hendrerit metus. Donec laoreet ipsum ac tristique tempus. Praesent faucibus consequat augue, eget congue metus volutpat et. Morbi ac leo erat. Donec quis risus non libero ornare vehicula. Aliquam sit amet erat eu est posuere fermentum non sed neque. In commodo tristique eros vitae porttitor.\n" +
                "\n" +
                "Sed non lacus bibendum, vehicula ipsum id, molestie libero. Suspendisse at scelerisque urna, gravida scelerisque urna. In ac tellus tellus. Aenean consectetur justo sit amet ultrices lobortis. Nunc enim leo, auctor id tempor nec, faucibus at velit. Nunc ornare neque eget ipsum auctor, sit amet interdum nunc tempor. Quisque vestibulum risus sed bibendum aliquet. Donec dictum elementum porttitor. Nunc nisi nisl, scelerisque sed euismod id, cursus vitae augue. Donec gravida ligula vel mauris consequat, a consectetur felis tincidunt. Ut vestibulum libero sed eros fermentum iaculis vel vel eros. Proin ullamcorper tristique arcu, sed tincidunt ipsum semper id. Quisque et semper sapien. Proin pulvinar ex sagittis enim ultrices efficitur. In congue elit vel tortor cursus, ultrices venenatis ipsum congue.\n" +
                "\n" +
                "Duis egestas cursus facilisis. Donec eget placerat magna, sit amet elementum massa. Pellentesque purus purus, rutrum vel pretium sed, accumsan eu augue. Pellentesque ultricies, urna id consequat tristique, lacus massa interdum arcu, vitae maximus massa orci a nisi. Morbi at convallis nunc. Curabitur in sem nec erat dictum tincidunt. Donec ornare felis ullamcorper dignissim efficitur. Etiam dignissim quam vitae neque volutpat, sit amet consectetur dui facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in velit non odio ultrices rutrum ornare vel sem. Aliquam vitae egestas massa, id imperdiet quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam venenatis massa quis finibus scelerisque. Ut volutpat arcu purus, id vulputate magna efficitur in. Nulla aliquam varius condimentum.\n" +
                "\n" +
                "Nunc aliquam tortor in fringilla blandit. Curabitur scelerisque ac augue quis fringilla. Aliquam rhoncus metus arcu, vitae tempor sapien rutrum vel. Aenean laoreet mauris sit amet felis dictum, tempor vehicula dui pretium. Integer odio augue, laoreet ac quam eu, ornare pharetra arcu. Pellentesque cursus pulvinar lorem, nec accumsan ipsum ullamcorper eu. Etiam dapibus egestas vehicula. Suspendisse blandit varius commodo.\n" +
                "\n" +
                "Mauris porttitor ex ac tortor dignissim, at aliquet leo gravida. Fusce congue semper hendrerit. In vitae mi elit. Cras suscipit mauris eu ex auctor, eget accumsan nulla eleifend. Ut finibus lorem nibh, ultricies venenatis purus luctus et. Duis nibh mauris, imperdiet vel odio nec, porttitor tempus massa. Mauris sagittis iaculis lorem.\n" +
                "\n" +
                "Sed eu sem placerat, finibus nulla non, egestas ante. Curabitur in molestie erat, sed volutpat mauris. Nam tristique lacinia tortor ut vulputate. Ut non enim condimentum, iaculis mauris et, vulputate libero. Nulla eu venenatis felis. Aenean tempor placerat efficitur. Nunc id massa ac magna euismod dapibus a ut diam. Nunc egestas vestibulum velit id laoreet. Sed ipsum mauris, dignissim quis est vitae, tristique dapibus urna.\n" +
                "\n" +
                "Vivamus lacinia nibh non rhoncus gravida. Nulla in ante quis ipsum cursus iaculis eleifend nec lectus. Praesent accumsan velit vitae iaculis vulputate. Etiam convallis eget risus at aliquam. Praesent vel urna eget metus vulputate aliquet. Phasellus ultrices vel justo ac accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce mattis nunc placerat lacus tempor, at gravida mi finibus. Vivamus eget pulvinar purus. Maecenas cursus mi sit amet auctor sagittis. Nullam vehicula elit a mauris porttitor, eu euismod tellus vulputate. Ut pellentesque congue efficitur. Suspendisse sed feugiat urna.\n" +
                "\n" +
                "Vestibulum in ex dictum mi aliquam consequat. Proin euismod elit ante, vitae posuere elit finibus nec. Maecenas eget lorem gravida, fringilla metus eu, fringilla neque. Fusce at velit lorem. Proin vel faucibus ipsum. Sed tincidunt volutpat lectus volutpat porta. Fusce eleifend vehicula malesuada. Donec laoreet orci id leo cursus mollis.\n" +
                "\n" +
                "Nullam eu velit nec lorem pellentesque ultrices. Etiam molestie lacinia sapien. In id dui sit amet nibh finibus congue id sed lorem. Nunc ullamcorper et enim ut tincidunt. Duis ac odio malesuada, ullamcorper libero in, commodo tortor. Nullam semper ultrices odio. Nullam ultrices metus in erat aliquet efficitur. Suspendisse posuere ipsum sit amet efficitur semper. Suspendisse tempus magna vel erat maximus semper. Nunc pretium nec dolor vel sodales. Etiam semper leo non ligula ultrices, quis sollicitudin tortor dictum. Aliquam congue varius lectus nec dignissim. Proin ut mattis leo.\n" +
                "\n" +
                "Maecenas blandit cursus sagittis. Sed magna mi, aliquam quis ante vel, convallis pharetra tellus. Duis ornare id dui sed consectetur. Sed nec arcu id justo euismod tincidunt. Integer accumsan condimentum leo, vel sagittis erat dignissim in. Sed eleifend quam in est porttitor, ac maximus augue vulputate. Curabitur imperdiet dolor id lorem sollicitudin, ac porttitor arcu placerat. In aliquam massa nec vulputate tempor. Duis laoreet fringilla dui, sit amet vehicula orci dignissim sit amet. Duis varius dolor rutrum, dictum mauris eget, pellentesque urna. Nunc malesuada et ligula in commodo. Aenean vestibulum tempus vehicula. Maecenas viverra non justo eu sollicitudin.\n" +
                "\n" +
                "Phasellus pretium risus sit amet nisl euismod fermentum. Mauris non diam ac est blandit ultrices sit amet eget mauris. Sed sapien eros, iaculis id pretium quis, tempus laoreet leo. Aliquam faucibus gravida ultrices. Proin condimentum tincidunt vulputate. Curabitur egestas porttitor risus sit amet consequat. Sed hendrerit est a sodales sollicitudin. Aliquam diam dui, gravida sed velit eu, blandit mollis enim.\n" +
                "\n" +
                "Etiam lectus ligula, tincidunt sit amet tincidunt sit amet, feugiat ac est. Nulla vitae mi nec libero sagittis venenatis. Mauris eu justo a mauris eleifend molestie. In non nunc ac nulla consectetur interdum ac quis dui. Maecenas varius interdum hendrerit. Ut maximus, mauris eu placerat feugiat, enim tortor porttitor arcu, non tristique leo tortor lacinia nisl. Integer eu odio tortor. Sed dignissim luctus dolor a hendrerit. Etiam nec nulla non nibh porta convallis. Maecenas et nisi et turpis tristique vestibulum vel quis ante. Vivamus feugiat mi at nunc tincidunt, vitae sollicitudin metus maximus. Fusce rhoncus sit amet turpis id feugiat. Nunc ex est, pulvinar vel varius id, lobortis nec magna.\n" +
                "\n" +
                "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec cursus posuere felis ac maximus. Suspendisse placerat pretium mauris. Nulla quis est scelerisque elit lobortis lobortis in vel ex. Duis at volutpat elit. Morbi condimentum dui lorem, at pulvinar ligula sagittis id. Donec luctus tortor sollicitudin mauris ultricies condimentum. Pellentesque non facilisis quam, at pharetra magna.\n" +
                "\n" +
                "Sed tincidunt ipsum orci, quis egestas lectus faucibus sed. Vivamus id ultricies est. Vivamus at enim et erat sollicitudin mollis a id justo. Cras interdum dapibus ornare. Maecenas imperdiet consequat arcu eget imperdiet. Integer in elementum sem. Vestibulum eget aliquet nulla, ut hendrerit odio. Pellentesque bibendum orci urna, sollicitudin facilisis justo convallis sed. Nullam sed diam pulvinar, pretium nulla ac, finibus nunc. Duis consequat orci et libero consectetur, non pretium nisi blandit.\n" +
                "\n" +
                "Quisque sodales fermentum bibendum. Morbi et tristique arcu. Vestibulum metus nulla, hendrerit eu pretium nec, congue ut tellus. Etiam hendrerit, lacus vitae posuere maximus, velit risus sagittis orci, in consectetur est libero nec elit. Vivamus euismod, tortor sit amet condimentum fringilla, nunc ex condimentum lacus, vitae tincidunt arcu est et libero. Duis ac ligula eu leo tincidunt euismod. Quisque tempor fringilla magna a laoreet. Fusce tristique, ex vitae tempor maximus, est nisl condimentum nisi, vitae convallis massa magna a urna. Fusce convallis nunc at tortor blandit mattis. Donec tincidunt venenatis consequat. Maecenas iaculis ligula sapien, non imperdiet dui tincidunt ut. Cras suscipit, diam id iaculis auctor, mauris nibh interdum diam, tincidunt vehicula nunc diam vel augue. Vivamus a ante eu nisl eleifend elementum sit amet in tortor. Suspendisse ornare venenatis luctus. Maecenas eget sollicitudin neque.\n" +
                "\n" +
                "In tempor egestas tristique. In varius, elit nec consequat finibus, nunc felis varius ex, vitae tempor erat sem et odio. Pellentesque non ipsum sem. Donec a est vel nibh pretium sagittis id sit amet libero. Ut tellus diam, eleifend ut dictum id, interdum et nibh. Etiam eu mollis mauris, sit amet elementum orci. Proin non sagittis mauris. Quisque vitae tempus ex, ut vestibulum mi. Vivamus dignissim dui vel pulvinar tempor. Quisque placerat est leo, nec malesuada lectus lacinia eu. In a neque vitae enim hendrerit dignissim sed eget eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent auctor egestas magna id hendrerit. Nam viverra, nibh sed sagittis sagittis, est augue tempus augue, et dapibus leo est at sapien.\n" +
                "\n" +
                "Quisque nec risus sit amet tellus interdum vulputate eget in mi. Integer consectetur molestie neque, eget aliquam neque blandit id. Quisque placerat nisl nisi, at pulvinar arcu elementum lacinia. Vestibulum ullamcorper finibus semper. Nam eu velit ac augue accumsan mollis. Integer consectetur, augue a varius lobortis, tortor ante venenatis purus, et viverra eros massa ut sem. Aliquam nec porttitor sem. Morbi vitae mi odio. Praesent vitae convallis tortor, ut lobortis enim. Pellentesque faucibus mollis orci consequat tempus. Mauris malesuada urna eget mi lacinia, id elementum enim volutpat. Vivamus aliquam lobortis felis, sed hendrerit lorem. Donec pharetra dolor vel leo sodales, sit amet hendrerit nunc commodo. Vivamus dignissim, velit auctor dapibus lacinia, erat augue imperdiet justo, et porta nisl nisl in neque.\n" +
                "\n" +
                "Duis dignissim non lectus sed sodales. Curabitur volutpat, ligula ac rutrum dignissim, ante tellus suscipit leo, nec condimentum neque ipsum eget augue. Quisque gravida lorem sed egestas ullamcorper. Vivamus sem mauris, volutpat a sagittis eget, consectetur id libero. Sed tincidunt sem ut ultrices iaculis. Vivamus quis bibendum lorem. Sed vitae auctor lorem. Etiam pharetra eget sem vitae luctus. Pellentesque ac eros pretium massa pellentesque elementum sit amet eget arcu. Nam et est vitae libero vestibulum sollicitudin. Mauris in rutrum sapien. Integer maximus commodo maximus.\n" +
                "\n" +
                "Integer quis nisi sit amet erat tempor gravida tincidunt sit amet odio. Nullam facilisis ipsum in aliquet venenatis. Etiam erat diam, rhoncus sit amet tincidunt ac, condimentum et diam. Ut venenatis magna nibh, eget porttitor quam sagittis vel. Duis non lorem vel velit scelerisque laoreet id eu diam. Mauris tempor tortor at quam placerat suscipit. Morbi faucibus sed nisi in egestas. Sed malesuada arcu sed quam hendrerit, quis luctus nisi interdum. Nam est elit, varius eget nisi a, tempor hendrerit orci. Donec fringilla finibus est quis tincidunt.\n" +
                "\n" +
                "Sed dui augue, mollis sit amet vulputate ac, egestas sed lectus. Nunc ornare at erat in gravida. Vivamus tincidunt lectus tortor, vulputate tempus augue ullamcorper non. Curabitur vel blandit arcu, eget scelerisque urna. In lacinia mattis porta. Fusce venenatis gravida laoreet. Ut et dignissim elit. Fusce ex velit, semper ac interdum nec, bibendum non est. Donec finibus neque ut dui suscipit, sed dignissim sapien venenatis. Cras nunc urna, tincidunt vitae bibendum a, porttitor et dui. Integer efficitur eros id justo lobortis, eu blandit nibh hendrerit. Vestibulum nec mi pharetra, facilisis nisi vitae, blandit diam. In hac habitasse platea dictumst.\n" +
                "\n" +
                "Fusce a nibh vel tortor imperdiet gravida et in ante. Etiam tristique, felis id congue volutpat, mauris mi posuere orci, in consequat mi felis ut mauris. Quisque sollicitudin est ut elementum fermentum. Morbi porttitor fringilla lectus, eu convallis nulla viverra eu. Vestibulum a purus vitae sem eleifend ullamcorper. Nulla tincidunt nisi et tortor volutpat aliquam. Nam eleifend eget est ac tempus. Nulla facilisi.\n" +
                "\n" +
                "Aliquam erat volutpat. Maecenas nec sem gravida, tincidunt ex sed, pharetra mi. Donec fringilla dignissim ipsum tempus tincidunt. Suspendisse potenti. Morbi scelerisque nibh nec posuere ultricies. Suspendisse laoreet, neque a euismod tristique, arcu dolor luctus ipsum, non lobortis sapien dui sed metus. Cras pretium pellentesque justo at consequat. Duis sit amet enim viverra, mattis lorem ut, rutrum odio. Morbi tincidunt eget eros vel ultrices. Integer in fermentum velit, eu fringilla libero. Donec laoreet lacus elementum eros aliquam condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer quam lacus, mollis eget eros at, feugiat consectetur dui. Mauris congue, massa consectetur tincidunt dignissim, erat justo ullamcorper sem, vitae venenatis eros justo at quam. Aenean at neque in odio elementum faucibus. Fusce tortor eros, bibendum ultricies hendrerit in, sagittis sit amet eros.\n" +
                "\n" +
                "Quisque sollicitudin quis nisi eu vehicula. Suspendisse pellentesque, mi ac feugiat tempus, ligula risus accumsan dui, ut posuere turpis lacus a sapien. Curabitur vel cursus lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur porttitor pharetra iaculis. Proin consequat ipsum vel quam hendrerit, congue sagittis neque vehicula. Nulla vel augue pulvinar arcu egestas eleifend at id libero. Nullam eget congue nisi, vitae luctus risus. Suspendisse mattis massa vel augue molestie pellentesque.\n" +
                "\n" +
                "Maecenas malesuada neque sit amet enim aliquet gravida. Etiam id metus euismod velit finibus egestas eu in leo. Fusce mattis tellus eu dignissim ornare. Duis sed tellus sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut in arcu dui. Donec erat magna, sollicitudin et viverra non, molestie vitae erat. Etiam pellentesque pharetra lacinia.\n" +
                "\n" +
                "Nam viverra posuere arcu vitae porttitor. Vestibulum volutpat id mauris ut tempor. Sed libero est, tempor eget metus eu, laoreet pretium massa. Praesent ut vehicula quam, sit amet dignissim urna. Duis dignissim lacus non ornare dignissim. Donec vel rutrum ipsum, eget ultricies sem. Nulla rutrum nunc a mi tincidunt, sit amet pretium lorem hendrerit. Maecenas laoreet sem id erat accumsan tempor vitae sed diam.\n" +
                "\n" +
                "In et finibus lorem, non rhoncus ligula. Duis id elementum justo. Ut efficitur, quam eget pellentesque suscipit, quam dolor congue metus, nec ornare elit velit at leo. Pellentesque massa risus, suscipit a orci ac, iaculis tincidunt orci. Morbi sed elementum ligula. Mauris blandit finibus turpis, eget tempus turpis bibendum vitae. Cras quis hendrerit enim, in sagittis quam. Vestibulum semper pretium lacus, eget vestibulum sapien elementum ut. Proin massa orci, blandit eget lacus sit amet, ultrices laoreet enim. Nunc id lectus condimentum, varius enim nec, laoreet orci. Integer suscipit quis massa ut posuere.\n" +
                "\n" +
                "Sed non justo ante. Praesent a varius urna. Vestibulum at diam sed nisl laoreet fermentum tempus non elit. Etiam id ornare orci, a maximus lorem. Donec massa tellus, pulvinar non ultrices nec, lacinia nec sem. Vestibulum sed lectus et massa sodales lobortis eget nec nisi. Donec nec felis rhoncus, placerat turpis vel, interdum augue. Vivamus bibendum arcu vel nisl convallis varius. Donec fringilla metus eu dignissim convallis. Vestibulum commodo lacus efficitur, feugiat justo quis, consectetur massa. Phasellus at bibendum mauris.\n" +
                "\n" +
                "Pellentesque pellentesque dui non tristique pellentesque. Duis cursus arcu porta vestibulum consectetur. Cras purus erat, efficitur sollicitudin hendrerit vitae, porta quis elit. In tempus mauris sed placerat egestas. Ut in neque maximus, pretium ante vel, laoreet arcu. Nulla a tellus quis sapien suscipit vehicula. Pellentesque sagittis malesuada lacus, a scelerisque orci consequat non.\n" +
                "\n" +
                "Nunc congue auctor laoreet. Nunc vel pulvinar odio. Praesent aliquam, tellus nec rutrum vulputate, velit quam semper tortor, at malesuada lorem metus at neque. Integer mollis pharetra elit, vitae iaculis erat suscipit et. Sed suscipit erat enim, sit amet tincidunt massa lobortis quis. Vestibulum mollis dapibus ex, ac fermentum metus ultrices eget. Nam sodales lectus suscipit laoreet euismod. Sed tincidunt, purus vel interdum pretium, magna elit laoreet purus, sed dapibus quam leo in nulla. Aenean accumsan leo sed volutpat tempor. Praesent in maximus dolor. Cras posuere, metus id vestibulum consequat, ligula ex congue massa, id laoreet purus quam ac purus. Nulla facilisi. Phasellus nec pharetra diam. Phasellus nibh mi, posuere at faucibus id, gravida eu nisl. Nulla facilisis eleifend commodo. Nunc eros enim, bibendum vel facilisis non, rutrum a neque.\n" +
                "\n" +
                "Vivamus sollicitudin lacinia magna id imperdiet. Etiam pellentesque rutrum purus, vitae congue metus efficitur consequat. Integer consectetur diam at fringilla lobortis. Ut eget mi pulvinar eros tempus sagittis in sit amet enim. Nam rutrum quam ac ante rutrum consequat. Nam accumsan arcu mi, eget suscipit erat ornare quis. Donec dictum venenatis dapibus.\n" +
                "\n" +
                "Nullam aliquam arcu elit. Duis lobortis commodo turpis id rutrum. Nunc luctus vitae mauris quis luctus. Vivamus interdum condimentum purus sed finibus. Sed imperdiet diam vitae justo pharetra, ullamcorper posuere risus pretium. Integer quis tincidunt massa, id ultricies urna. Phasellus ac scelerisque odio. Nulla vitae lobortis risus, et mattis arcu. Proin id libero et ex blandit auctor. Suspendisse mauris lorem, viverra nec vestibulum ac, tristique non sem.\n" +
                "\n" +
                "Vivamus semper tortor vel sem finibus tempor. Nullam eget volutpat ante. Proin elementum ornare congue. Quisque non felis fringilla, fermentum diam non, laoreet ligula. Nullam venenatis elit et nulla laoreet, ac convallis dolor egestas. Mauris facilisis ligula non quis.";
        String str3 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a luctus dui, et efficitur lectus. Phasellus vel fermentum turpis. Suspendisse rhoncus massa arcu, et elementum elit maximus sed. Vestibulum ligula odio, pretium vitae elementum et, luctus vel massa. Cras eros odio, condimentum ultrices tristique at, pellentesque sit amet magna. Nullam ullamcorper urna et mi fermentum, id congue tortor luctus. Nulla sit amet mi imperdiet nisi molestie accumsan vel vitae elit. Aliquam sodales lorem sed volutpat sodales. Sed luctus sapien quis lorem commodo, a varius neque bibendum. Fusce eget sagittis tellus. Vivamus suscipit congue enim, nec lacinia leo consequat vitae. Sed in elit ac justo pellentesque ultricies. Morbi semper aliquet risus, hendrerit molestie lectus ornare quis. Proin consectetur interdum venenatis. Nullam condimentum a libero eget interdum. Sed laoreet enim viverra metus accumsan eleifend.\n" +
                "\n" +
                "Nulla id accumsan mi, quis gravida dolor. Nulla a augue at ligula ultricies interdum. Phasellus accumsan scelerisque orci, et consequat tortor egestas quis. In hac habitasse platea dictumst. Donec convallis risus quis dapibus ornare. Integer non dolor sodales, convallis tellus laoreet, viverra augue. Suspendisse tincidunt mi metus, sed volutpat nunc volutpat id. Proin hendrerit convallis nunc, id faucibus erat sodales nec. Aenean condimentum sed erat sit amet cursus. Morbi laoreet ligula sed neque lobortis luctus. Fusce at sagittis felis. Sed at sem sit amet ex dictum feugiat a non nisl. Vivamus semper fermentum consequat.\n" +
                "\n" +
                "Pellentesque condimentum magna sed est rutrum, id molestie tellus aliquet. Pellentesque vitae odio lorem. Vivamus et tristique dolor. Sed faucibus ligula tortor, sit amet vehicula risus tincidunt at. Cras commodo euismod orci vel feugiat. Nunc rhoncus felis nec viverra mollis. Nam rutrum feugiat viverra. Sed euismod ornare dolor, id tincidunt dui ultrices sit amet. Fusce a tristique ex, ut interdum justo. Quisque elementum nunc pulvinar purus pretium venenatis. Nunc sed ultrices eros, at ultrices justo. Mauris sit amet dapibus leo, a vehicula est.\n" +
                "\n" +
                "Nam scelerisque urna nisl, non bibendum sapien consequat non. Duis tempus nisl eget pellentesque venenatis. Vestibulum aliquet gravida fermentum. Donec ac malesuada nibh, venenatis consectetur enim. Vivamus varius fermentum diam a ullamcorper. Praesent hendrerit orci vitae mauris facilisis, non auctor sem volutpat. Nulla semper, arcu non posuere luctus, lacus lacus vestibulum felis, et venenatis mauris ipsum in arcu. Etiam a elementum massa, ut sollicitudin dui. Pellentesque a rhoncus magna, dapibus accumsan libero. Curabitur rutrum, tortor ac ornare faucibus, mauris urna sollicitudin metus, at accumsan nulla urna a purus. Curabitur tempor lacus sed eros egestas, vel mattis lacus egestas.\n" +
                "\n" +
                "Pellentesque rhoncus maximus blandit. Donec in risus sed arcu suscipit condimentum et vel velit. Fusce accumsan sem pharetra eleifend tincidunt. Sed nisl est, lacinia vel accumsan vel, scelerisque dignissim ipsum. Donec varius blandit lorem in fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla facilisi. Ut in tortor tortor. Nulla nec augue est.\n" +
                "\n" +
                "Sed sit amet tincidunt nisi. Vivamus dapibus lorem convallis ante scelerisque imperdiet. Nullam molestie est et leo mollis auctor. Proin eu velit a ligula suscipit varius. Proin augue magna, tempor sed mauris quis, maximus porttitor sapien. Cras hendrerit dolor vel venenatis interdum. Praesent rutrum dictum pellentesque. Integer hendrerit magna euismod neque aliquet, id sagittis dolor euismod. Nullam congue hendrerit augue lacinia posuere. Donec ipsum odio, consequat sit amet imperdiet sit amet, malesuada et ipsum.\n" +
                "\n" +
                "Aliquam ut bibendum ipsum. Nullam eget molestie ligula, vel ultrices lectus. Duis commodo iaculis quam a porttitor. Donec et velit vitae nibh fringilla sagittis. Morbi facilisis erat sed mi aliquet, eget lobortis diam sollicitudin. Mauris lacinia rhoncus pharetra. Aenean rutrum blandit lobortis. Mauris at viverra sem. Fusce hendrerit sapien nulla, in dictum ligula scelerisque non. Aliquam erat volutpat. Curabitur ornare sodales nibh, vel tempor erat tristique et. In malesuada cursus orci sit amet commodo. Nunc at vulputate diam. Pellentesque in mi at sapien interdum pretium quis ac dui.\n" +
                "\n" +
                "Morbi magna nunc, condimentum sodales est tincidunt, fermentum semper purus. Integer ac congue augue, id aliquet libero. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis blandit et lectus eu pharetra. Aenean vel massa vitae est condimentum tincidunt. Duis vehicula elit auctor lectus accumsan, sed pretium ipsum porttitor. Cras non velit velit. Proin eu consectetur velit. Vivamus ut ultricies sapien. Donec vehicula, augue a ultrices ornare, velit ante volutpat orci, vitae volutpat tortor augue sit amet justo. Maecenas vitae dui nisl.\n" +
                "\n" +
                "Duis eget viverra velit. Etiam nec enim eget sem commodo dictum ut eget augue. Sed tincidunt ornare ipsum, ut iaculis tellus porta sed. Ut porttitor lobortis molestie. Nulla viverra diam a enim pulvinar, non tincidunt ligula ultricies. Praesent vitae pharetra mi, nec elementum neque. Aenean congue orci in commodo finibus. Aliquam iaculis venenatis nisi, non tempus diam.\n" +
                "\n" +
                "Aenean a nunc in ante accumsan ultrices at placerat tortor. Suspendisse accumsan justo sed pretium elementum. Etiam laoreet odio id libero congue molestie. Proin imperdiet congue lorem interdum pharetra. Pellentesque ut imperdiet orci. Sed lacinia turpis quis mi mattis, sit amet suscipit ante vulputate. Suspendisse vel purus ex. Ut et justo nec velit pulvinar fermentum. Nulla eu ipsum id nunc feugiat accumsan. Cras rutrum lacus non ullamcorper commodo. Curabitur faucibus ultricies porta.\n" +
                "\n" +
                "Proin sit amet efficitur nisi, quis tristique ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis nec lorem turpis. Pellentesque lacinia lacus nisl, eu varius massa aliquet ut. Nulla eget lobortis nunc, luctus porta metus. Nullam tincidunt nibh diam, et fringilla ex varius vitae. Nullam at dui quis velit eleifend ultricies vitae ac mauris. Integer facilisis finibus turpis, in ullamcorper purus.\n" +
                "\n" +
                "Sed suscipit eros id sem suscipit, sit amet varius mi aliquet. Nunc odio leo, mattis id efficitur a, gravida in orci. Mauris vel metus vulputate, euismod nibh vitae, gravida mauris. Nulla in mauris tortor. Aliquam ut urna eu lectus suscipit facilisis. Vestibulum at lacus ac erat facilisis dignissim non a metus. Vestibulum consequat quam quis dolor malesuada, id efficitur elit tempor. Curabitur eget semper orci. Etiam malesuada neque sed iaculis porta. Ut accumsan mauris nec nisl varius vehicula. Donec vestibulum dolor vel lacus lobortis, ac pellentesque velit cursus.\n" +
                "\n" +
                "Ut ac urna vitae diam vulputate semper eget quis ligula. Etiam nec varius turpis. Integer varius ante magna, sit amet maximus nulla fermentum eget. Praesent a ligula ullamcorper, volutpat turpis et, tempor felis. Cras placerat, dolor rutrum vehicula pretium, quam mauris vestibulum turpis, in rutrum augue nisi sit amet nisi. In ut risus nec dolor ornare tristique sit amet eget libero. Quisque non vestibulum enim. Curabitur ante metus, suscipit vel luctus ac, mollis vitae tortor. Morbi tincidunt magna at erat condimentum, quis rhoncus dui eleifend. In eget nisl et urna accumsan aliquam at a dui. Morbi elementum lacinia odio, ac accumsan dolor tempor sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam et mattis metus. Curabitur mollis eget lectus vitae congue.\n" +
                "\n" +
                "Pellentesque maximus vitae quam id gravida. Sed porta metus nunc, et eleifend felis aliquet non. Nulla facilisi. Suspendisse potenti. Nullam finibus varius ultricies. Aenean fringilla ut tellus non mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec vitae sem et lectus volutpat dignissim vitae ut odio. Donec pellentesque tristique laoreet. Maecenas vestibulum eu nisl vitae rhoncus. Suspendisse iaculis, lectus feugiat iaculis egestas, urna nunc sagittis odio, nec consectetur dolor nulla bibendum quam. Integer metus tellus, vehicula ac elementum eu, consequat non dui. Integer dictum enim augue, auctor feugiat magna elementum vitae. Aenean sodales porta imperdiet. Nam nisi lacus, mattis nec lobortis at, faucibus eget enim.\n" +
                "\n" +
                "Vestibulum massa ante, sagittis sed tempus eget, finibus sed nulla. Cras volutpat maximus justo vel rutrum. Vivamus eget convallis lacus. Nunc faucibus feugiat dolor, vel aliquam ante mollis et. Donec posuere velit sit amet egestas lobortis. Vivamus et nunc aliquam, egestas sem vitae, iaculis nibh. Suspendisse mattis dui eget ligula rhoncus bibendum. Praesent mattis fringilla porta.\n" +
                "\n" +
                "Aliquam feugiat turpis vitae tincidunt lacinia. Nam varius dapibus sagittis. Integer blandit est interdum, pretium mi a, suscipit nunc. Curabitur tincidunt neque vel sapien luctus convallis. Curabitur lectus nulla, malesuada a ligula ut, dapibus dictum mi. Quisque mollis tincidunt tortor, id venenatis ante molestie id. Nulla velit eros, porta vitae tincidunt quis, ultricies faucibus ex.\n" +
                "\n" +
                "Suspendisse metus nulla, ultricies in ligula a, iaculis gravida metus. Nunc turpis neque, vestibulum sed velit eu, semper egestas nisl. Nullam efficitur venenatis mattis. Duis feugiat aliquam ipsum, ac tempor massa iaculis non. Proin blandit metus vel augue vestibulum pharetra. Nam suscipit enim venenatis volutpat fringilla. Fusce feugiat velit vitae nulla porttitor tempus. Donec elementum nec diam et viverra.\n" +
                "\n" +
                "Sed non leo dapibus, dictum diam suscipit, suscipit lorem. Curabitur commodo arcu arcu, vitae hendrerit magna lobortis sed. Etiam viverra, erat a ullamcorper bibendum, tortor tortor pellentesque ligula, vitae ultrices libero nunc eget nisl. In viverra posuere risus non placerat. Proin cursus tortor vitae neque dictum, sit amet lacinia elit maximus. Quisque imperdiet elit eu felis viverra, vitae volutpat.\n" +
                "\n";
        String str1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tristique dictum tortor nec maximus. Aenean a nunc sodales, commodo nunc ac, consequat erat. Cras condimentum sem eget semper congue. Vivamus hendrerit quam at ante bibendum scelerisque. Donec gravida sem eget lectus posuere vulputate. Nam finibus dictum volutpat. Praesent turpis tortor, consectetur et odio sit amet, maximus viverra urna. Vestibulum gravida, elit at malesuada tincidunt, justo augue tempus urna, eu dapibus sapien dui vel elit. Vivamus ut vulputate ligula, dapibus eleifend lorem. Curabitur consequat augue et nisi luctus, id posuere lorem rhoncus. Nulla varius, sapien ac dictum lacinia, quam neque vestibulum libero, et malesuada orci felis a orci. Integer vestibulum nibh in semper imperdiet. Phasellus elementum lorem sodales turpis scelerisque suscipit. Morbi sem massa, vestibulum ac auctor sit amet, lobortis id lorem. Aliquam imperdiet sollicitudin magna quis consectetur.\n" +
                "\n" +
                "Cras non ipsum nisi. Pellentesque vel feugiat elit, vel tincidunt erat. Vivamus a efficitur enim. Vivamus id sem sapien. Proin vel augue sed diam bibendum pellentesque. Donec laoreet dolor ac mattis aliquet. Quisque in eros vel purus finibus tristique sed ac massa. Integer vitae urna sed urna sodales dapibus.\n" +
                "\n" +
                "In sed tortor commodo, ornare justo et, porttitor ligula. Donec varius odio sed eros tincidunt, quis placerat orci laoreet. Aliquam elementum, orci et ultricies bibendum, massa arcu fermentum orci, vitae semper diam orci in elit. Curabitur feugiat lorem eget neque rutrum dapibus. Fusce eget augue sed felis pretium tempus. Ut lorem lorem, consectetur eu magna quis, tincidunt tempus est. Vestibulum id eleifend mauris. Sed lorem metus, blandit quis vulputate at, placerat in sapien. Fusce sit amet dui nec risus egestas auctor. Quisque pharetra nunc ex, vel viverra nunc efficitur at. Phasellus cursus quis arcu non ultrices. Cras massa velit, pulvinar et dictum vitae, luctus et lectus. Aenean iaculis luctus orci aliquam.";

        String str2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus risus eu metus condimentum, nec fringilla nisi gravida. Maecenas ut augue mollis, maximus leo sit amet, posuere felis. Integer sed tristique sem. Nulla facilisi. In hac habitasse platea dictumst. Morbi eros lorem, consequat eu enim blandit, tempor commodo eros. Mauris id urna magna. Vivamus non nibh sed sem finibus feugiat in sit amet lectus. Quisque fringilla iaculis nunc, id placerat turpis bibendum vitae. Fusce ornare magna a blandit imperdiet.\n" +
                "\n" +
                "Phasellus at risus ac odio sagittis varius. Ut nec arcu quis velit blandit fermentum lacinia a nisi. Proin tristique maximus mi eget scelerisque. Sed viverra faucibus mauris, nec egestas ipsum consectetur dignissim. Ut consectetur laoreet ante, vel commodo purus ultricies vitae. Donec maximus ornare semper. Maecenas sollicitudin sollicitudin est id porta. Mauris finibus ligula ac vehicula venenatis. Nullam cursus scelerisque nisi, non tempor orci sollicitudin ac. Curabitur in ipsum mollis, placerat nibh eu, sollicitudin diam. Aliquam non ultrices diam. Morbi eget elit at erat commodo tincidunt. Donec aliquet quis ligula in scelerisque. Nulla vulputate quam id ipsum consequat molestie. Suspendisse dignissim tempor quam. Donec non laoreet leo.\n" +
                "\n" +
                "Donec tempus risus id dui maximus auctor. Praesent efficitur auctor odio, quis dignissim quam iaculis quis. Duis dapibus tempus odio ut sagittis. Aliquam erat volutpat. Proin id eros feugiat, congue quam ut, auctor arcu. Phasellus et orci hendrerit, accumsan leo ac, rhoncus turpis. Nullam cursus molestie dui, nec fringilla risus facilisis pretium. Donec quam ante, lobortis vitae dictum eget, facilisis nec orci. Ut tempus lectus in malesuada egestas. Suspendisse ipsum libero, rhoncus sit amet ipsum eget, egestas accumsan dolor.\n" +
                "\n" +
                "Ut ultricies orci id efficitur posuere. Nullam hendrerit tempor felis. Vivamus venenatis sapien sed imperdiet volutpat. Pellentesque tempus nunc id elementum fermentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis bibendum rutrum sagittis. Etiam vitae eros tellus. Nam et elementum enim. Vivamus sit amet magna vitae lorem tincidunt tincidunt. Aenean accumsan venenatis aliquet.\n" +
                "\n" +
                "Pellentesque cursus rutrum risus, ut blandit ex placerat maximus. Cras ac nisl ut tortor convallis tincidunt id ac metus. Sed eget massa at tortor porttitor rhoncus vel non urna. Aliquam congue risus ut lacus euismod eleifend ac at erat. Phasellus eu orci efficitur, ullamcorper leo vel, fringilla purus. Duis commodo purus mauris, eu finibus lectus tincidunt at. Morbi consectetur, ex sit amet vulputate egestas, libero justo venenatis arcu, ac rutrum massa metus vitae erat. Phasellus ullamcorper ornare neque. Vestibulum purus felis, malesuada nec libero et, accumsan tincidunt est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut tempus, nulla non gravida scelerisque, ex ex tempus velit, nec vehicula diam nunc sit amet ipsum. Cras dolor ligula, elementum ut risus et, aliquam auctor justo. In ex nisl, sagittis eu orci vitae, lacinia fermentum mauris. Nulla facilisi. Donec quam nisi, vulputate eu erat vel, vulputate porta risus.\n" +
                "\n" +
                "Aenean a consequat quam, eu fermentum mauris. Maecenas ullamcorper, nibh vitae elementum viverra, lacus diam ultricies purus, a ullamcorper magna velit et arcu. Nam hendrerit vel nisl id blandit. Sed efficitur et massa vitae posuere. Proin sed fringilla velit. In dapibus sagittis diam, id placerat lectus feugiat nec. Integer molestie mattis convallis. Duis eu congue ante, at sollicitudin quam. In ultricies, ipsum sit amet rutrum efficitur, dolor lorem tincidunt nulla, et ornare diam ligula eget justo. Sed odio purus, vestibulum sit amet viverra sit amet, aliquam sit amet ante.\n" +
                "\n" +
                "Sed molestie maximus aliquam. Nam dignissim ligula egestas justo venenatis finibus. Nulla sed pretium nisl. Donec dictum luctus dictum. Aenean quis gravida ipsum. Quisque fringilla ac neque a bibendum. Vestibulum ornare lacinia suscipit. Suspendisse commodo auctor libero lacinia ornare. Pellentesque nec arcu mi.\n" +
                "\n" +
                "Etiam tempus felis at diam condimentum elementum. Sed ullamcorper placerat est a mollis. Curabitur elementum odio eget ex tincidunt, vitae tempor lacus suscipit. Vivamus arcu purus, finibus eu lacus et, fringilla vehicula urna. Maecenas luctus posuere nulla in faucibus. Nam dictum sapien a dapibus tristique. Morbi lacinia, ligula in fringilla varius, ligula odio laoreet metus, vel facilisis sapien felis id tellus. Vivamus hendrerit bibendum tellus convallis fringilla. Donec mollis nisl lacus, sit amet ultrices urna laoreet eget. Donec viverra sollicitudin fringilla. Integer quis eros tortor. Curabitur ut nisi urna. Praesent aliquet quam consequat metus aliquet finibus consectetur at mauris. Curabitur viverra dictum mauris ac rhoncus. Quisque eleifend diam nisl, eleifend mattis eros lacinia in. Praesent eget arcu nec purus sollicitudin ullamcorper sed quis quam. Phasellus convallis vestibulum ipsum, eget duis.";
        E1 e1 = new E1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20));
        E1 e2 = new E1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20));
        E1 e3 = new E1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20));
        E1 e4 = new E1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20));
        E1 e5 = new E1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20));
        E1 e6 = new E1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20));
        E1 e7 = new E1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20));
        E1 e8 = new E1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20));
        E1 e9 = new E1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20));
        E1 e10 = new E1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20));
        List<E1> empList = List.of(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10);

        P1 person = new P1(RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), RandomStringUtils.randomAlphanumeric(20), empList, null);

        ThreadLocalRandom.current().nextInt(0, 10000);
        E2 a1 = new E2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000));

        E2 a2 = new E2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000));
        E2 a3 = new E2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000));
        E2 a4 = new E2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000));
        E2 a5 = new E2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000));
        E2 a6 = new E2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000));
        E2 a7 = new E2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000));
        E2 a8 = new E2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000));
        E2 a9 = new E2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000));
        E2 a10 = new E2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000));
        List<E2> empList1 = List.of(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10);

        Map<Integer, E2> m1 = new HashMap<>();
        m1.put(ThreadLocalRandom.current().nextInt(0, 10000), a1);
        m1.put(ThreadLocalRandom.current().nextInt(0, 10000), a2);
        m1.put(ThreadLocalRandom.current().nextInt(0, 10000), a3);
        m1.put(ThreadLocalRandom.current().nextInt(0, 10000), a4);
        m1.put(ThreadLocalRandom.current().nextInt(0, 10000), a5);
        m1.put(ThreadLocalRandom.current().nextInt(0, 10000), a6);
        m1.put(ThreadLocalRandom.current().nextInt(0, 10000), a7);
        m1.put(ThreadLocalRandom.current().nextInt(0, 10000), a8);
        m1.put(ThreadLocalRandom.current().nextInt(0, 10000), a9);
        m1.put(ThreadLocalRandom.current().nextInt(0, 10000), a10);

        P2 person1 = new P2(ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), ThreadLocalRandom.current().nextInt(0, 10000), null, null);

        MemoryAgent memoryAgent = new MemoryAgent();
//        DefaultSerializer<Object> serializer = new DefaultSerializer<>();
        Kryo kryo = new Kryo();
        kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
        kryo.setRegistrationRequired(false);

//        System.out.println("CustomSizeEstimator: " + CustomSizeEstimator.sizeOf(person1));
//        System.out.println("CustomSizeEstimator1: " + CustomSizeEstimator1.sizeOf(person1));
////        System.out.println("CustomSizeEstimator2: " + CustomSizeEstimator2.sizeOf(person1));
//        System.out.println("CustomSizeEstimator3: " + CustomSizeEstimator3.sizeOf(person1));
//        System.out.println("UnsafeUtil: " + UnsafeUtil.size(person1));
//        System.out.println("DefaultSerializer: " + serializer.serialize(person1).array().length);
//        System.out.println("MemoryAgent: " + memoryAgent.getObjectSize(person1, false));

//        System.out.println("CustomSizeEstimator: " + CustomSizeEstimator.sizeOf(person));
//        System.out.println("CustomSizeEstimator1: " + CustomSizeEstimator1.sizeOf(person));
//        System.out.println("CustomSizeEstimator3: " + CustomSizeEstimator3.sizeOf(person));
//        System.out.println("UnsafeUtil: " + UnsafeUtil.size(person));
//        System.out.println("DefaultSerializer: " + serializer.serialize(person).array().length);
//        System.out.println("MemoryAgent: " + memoryAgent.getObjectSize(person, false));


//        String str = new String("test1234");
//        System.out.println("CustomSizeEstimator: " + CustomSizeEstimator.sizeOf(str));
//        System.out.println("CustomSizeEstimator1: " + CustomSizeEstimator1.sizeOf(str));
////        System.out.println("CustomSizeEstimator2: " + CustomSizeEstimator2.sizeOf(str));
//        System.out.println("UnsafeUtil: " + UnsafeUtil.size(str));
//        System.out.println("DefaultSerializer: " + serializer.serialize(str).array().length);
//        System.out.println("MemoryAgent: " + memoryAgent.getObjectSize(str, false));

        P p = new P();
//        System.out.println(ObjectSizer.sizeOf(p));
//        TestObject testObject = new TestObject();
//        System.out.println("CustomSizeEstimator: " + CustomSizeEstimator.sizeOf(testObject));
//        System.out.println("CustomSizeEstimator1: " + CustomSizeEstimator1.sizeOf(testObject));
//        System.out.println("CustomSizeEstimator3: " + CustomSizeEstimator3.sizeOf(testObject));
//        System.out.println("CustomSizeEstimator4: " + CustomSizeEstimator4.sizeOf(testObject));
//        System.out.println("UnsafeUtil: " + UnsafeUtil.size(testObject));
//        System.out.println("ObjectSizer: " + ObjectSizer.sizeOf(testObject));
//        System.out.println("DefaultSerializer: " + serializer.serialize(testObject).array().length);
//        System.out.println("MemoryAgent: " + memoryAgent.getObjectSize(testObject, false));
//
//        System.out.println("CustomSizeEstimator: " + CustomSizeEstimator.sizeOf(str4));
//        System.out.println("CustomSizeEstimator1: " + CustomSizeEstimator1.sizeOf(str4));
//        System.out.println("CustomSizeEstimator3: " + CustomSizeEstimator3.sizeOf(str4));
//        System.out.println("CustomSizeEstimator4: " + CustomSizeEstimator4.sizeOf(str4));
//        System.out.println("UnsafeUtil: " + UnsafeUtil.size(str4));
//        System.out.println("ObjectSizer: " + ObjectSizer.sizeOf(str4));
//        System.out.println("DefaultSerializer: " + serializer.serialize(str4).array().length);
//        System.out.println("MemoryAgent: " + memoryAgent.getObjectSize(str4, false));

        String testStr = RandomStringUtils.randomAlphanumeric(1000000);

        AtomicHistogram histogram = new AtomicHistogram(1, 1000000000, 2);
        for (int i = 1; i <= 100000; i++) {
            long s = System.nanoTime();
//            serializer.serialize(testStr);
//            CustomSizeEstimator1.sizeOf(str4);
//            CustomSizeEstimator.sizeOf(str4);
//            memoryAgent.getObjectSize(str4, false);
            histogram.recordValue(System.nanoTime() - s);
        }

        System.out.println("P99: " + histogram.getValueAtPercentile(99));
        System.out.println("P95: " + histogram.getValueAtPercentile(95));
        System.out.println("P90: " + histogram.getValueAtPercentile(90));
        System.out.println("Mean: " + histogram.getMean());
        System.out.println("Count: " + histogram.getTotalCount());

    }

}
